### ISSUE TITLE
module should support pkgng first run on FreeBSD 10

### ISSUE THREAD

**Issue by rtyler** [xaque208/puppet-pkgng#12]
On FreeBSD 10, the first thing that happens when you run `pkg` is that it prompts the user to self-update.

The module should probably handle that properly

**Comment by xaque208** [comment]
I don't believe this to be an issue any longer.  I also wonder now that pkg seems to be required for ports builds, how one would get puppet installed without pkg.  I'm going to close this out.  If there is disagreement here, please reopen.
