### ISSUE TITLE
pkg in alternate locations

### ISSUE THREAD

**Issue by jhujhiti** [xaque208/puppet-pkgng#23]
Currently, this assumes that pkg is located in /usr/local. The ports system allows users to change this location with the LOCALBASE knob in make.conf, which I have done. Of course, the module fails because there are several "/usr/local"s hard-coded.

I'm fairly new to Puppet, but I couldn't wrap my head around how best to implement this as a user-configurable setting. I don't think that automatically using LOCALBASE from /etc/make.conf is safe, because this won't necessarily be set if ports are 100% installed from binary packages.

**Comment by xaque208** [comment]
I belive this can be done outside of this module.  Setting the required make.conf varaibles, and perhaps building pkg poudriere would help here.  This is not something I expect this module to handle though.
