### ISSUE TITLE
module should work with the new location of the pkg configuration in 10.0-RELEASE

### ISSUE THREAD

**Issue by rtyler** [xaque208/puppet-pkgng#27]
The configuration is now in `/etc/pkg/FreeBSD.conf`, so all the logic in `manifests/init.pp` and the provider around tracking `/usr/local/etc/pkg.conf` needs to be updated

**Comment by xaque208** [comment]
I do not believe this to be an issue any longer, and was resolved long ago.

**Comment by mengesb** [comment]
Thanks Zach
