### ISSUE TITLE
purge_repos_d=>true should purge /etc/pkg

### ISSUE THREAD

**Issue by mpounsett** [xaque208/puppet-pkgng#49]
pkg leaves a default FreeBSD repository file in /etc/pkg which should be purged when purge_repos_d is set to true, in addition to /usr/local/etc/pkg/repos

**Comment by fraenki** [comment]
I think this issue should be closed, because this feature was implemented some time ago :)

**Comment by mpounsett** [comment]
Yeah, it looks like this was fixed back in July.
