### ISSUE TITLE
Doesn't work if pkgng version isn't latest

### ISSUE THREAD

**Issue by strangelittlemonkey** [xaque208/puppet-pkgng#62]
If pkgng isn't the latest version, it forces you to install prior to allowing you to do package installations, so invoking this on a fresh system will repeatedly fail.

**Comment by xaque208** [comment]
What version is failing you?  We could do special things for that version number if that would help.

**Comment by leepa** [comment]
We use this module in production and haven't experienced this issue.

**Comment by strangelittlemonkey** [comment]
1.4.10->1.4.11

With any version of pkgng, when a newer version of pkg exists, it forces the installation of that first, but the module has no check for that to see on update of cache of pkg is out of date and requiring update first.

**Comment by leepa** [comment]
Even if that's the case (we've had it just auto-upgrade so again wondering what's different) then you can use the `<| |>` syntax using anchors to achieve it without using the `require =>` on every package entry.

**Comment by strangelittlemonkey** [comment]
True, but a kludge is a kludge. Users shouldn't have to compensate for something that the module managing the package management system should be taking care of for them, I'm working on a patch to check if pkg has a newer version on invocation of the install method so it then diverts and installs pkg first and then continues.

**Comment by xaque208** [comment]
I don't believe this to be an issue any longer.  Please re-open with more data if I'm incorrect.
