### ISSUE TITLE
Order of operations problem with Puppet 4

### ISSUE THREAD

**Issue by mpounsett** [xaque208/puppet-pkgng#77]
In Puppet 4.x after the pkgng provider was incorporated into the core there is an order of operations problem that causes failed, or very long puppet runs.   This is tested with puppet 4.5.1 and zleslie/pkgng 1.1.1.

In my setup the pkgng class is included in site.pp like this:

``` puppet
class { 'pkgng':
  purge_repos_d => true,
}
```

I then include a pkgng::repo resource on FreeBSD hosts to define a local repository.

In this case, the order of operations appears to be:
1. purge repositories (purge_repos_d true) 
2. update/install packages
3. process pkgng::repo objects

There are two very painful failure modes with this.

First, on a system where the existing repository is being completely replaced with a local repository (possibly a new system with the default FreeBSD repository), the old repository is deleted, then packages are updated, then the new repository is installed.   The core pkgng provider fails badly if no repository is present (see https://groups.google.com/d/topic/puppet-users/ZtfxbkCEyWc/discussion).  There's no easy way to recover from this within puppet.  Since the agent run fails at the point that the pkgng provider errors out, the repo resource never gets created.  The only fix is to use some other process to create the proper repository config files on all the affected systems.

In the second failure mode, if a repository host or path is being updated, the agent run takes a very long time while all of the package version checks individually time out, before the repository is updated at the end of the agent run.

I'm not sure what the fix is for this.  There at least needs to be a way to swap the order of pkgng::repo handling and package updates.  Preferably the purge of unmanaged repo resources would happen at the same time as the update of managed repo resources.

**Comment by xaque208** [comment]
Thank you for the report.  I too have noticed this, but will take a closer look at a potential fix.

I suspect potential fixes include:

1. Fix the pkgng provider to fail gracefully when no repos are found.  This should include a fixture upstream and a test to resolve this.
2. Document a resource override that will ensure order of resources.  The pkg package may present a challenge here.
3. Look at ensuring the pkgng::repo resources are present before package installation.

The first one seems like something that just needs to happen.  The others might be touchy given that pkg is a package.

**Comment by xaque208** [comment]
I've submitted a PR upstream that should resolve the issue of Puppet failing. https://github.com/puppetlabs/puppet/pull/5285

**Comment by xaque208** [comment]
The upstream work has been merged.  Its unclear which version of Puppet this will be released in, but I'll bump the port version for this change.

**Comment by smortex** [comment]
Maybe adding a relationship with [collectors](https://docs.puppet.com/puppet/5.0/lang_collectors.html) in order to explicitly manage packages after repos would make sense.

Something like:
```
Pkgng::Repo <| |>
-> Package <| provider = 'pkgng' |>
```

**Comment by xaque208** [comment]
I've just tested the collector method and was not able to get this to work correctly.  I also tried a few other incantations of expressing the same desire.  It seems like even the following would work in `site.pp`, but it doesn't in my environment.

```puppet
Pkgng::Repo <||> -> Package <| provider == 'pkgng' |>
```

Alternatively, I thought about putting some kind of ordering in the `repo.pp`.

```puppet
File["/usr/local/etc/pkg/repos/${name}.conf"] -> Package <| provider = 'pkgng' |>
```
Neither strategy worked for me.  It seems like it could be a scoping issue, but I'm not certain why the ordering doesn't work out correctly.

Its possible we could do some kind of autorequire in the provider too.

**Comment by smortex** [comment]
Quick guess, when `Pkgng::Repo` configs are applied, two things happen:

  * `Packages` resources are "unlocked" and
  * `Exec['pkg update']` is notified.

But since there is no ordering for these two actions, nothing prevents the `Exec` to happen *after* the `Package` are applied…

I think that changing the dependency to the following should work as we expect (can't test before Wednesday… looooong week-end here 😄 ):
```
Exec['pkg update'] -> Package <| provider = 'pkgng' |>
```

**Comment by smortex** [comment]
Okay, did more test, and the answer seems to be basically here: https://puppet.com/docs/puppet/5.5/lang_collectors.html

> **Note:** Collectors can search only on attributes that are present in the manifests, and cannot read the state of the target system. For example, the collector `Package <| provider == yum |>` collects only packages whose `provider` attribute is explicitly set to `yum` in the manifests. It does not match packages that would default to the `yum` provider based on the state of the target system.

Changing the dependency to…

```puppet
Exec['pkg update'] -> Package <| provider == 'pkgng' or provider == undef |>
```
…seems to do the right thing.

**Comment by xaque208** [comment]
Ah, the undef was what I was missing.  This seems to correct the issue.  Thanks for looking into it!

**Comment by smortex** [comment]
> Ah, the undef was what I was missing.
Hehe :-) I also missed it and it took me quite some time to find-out the culpit!
