### ISSUE TITLE
Code not in sync with puppet Forge?

### ISSUE THREAD

**Issue by SirDice** [xaque208/puppet-pkgng#84]
It looks like the forge.puppet.com module is the code from 1.1.1 but with a 1.2.0 version string. Something doesn't add up.

puppet module install --modulepath /usr/local/etc/puppet/code/site_modules zleslie-pkgng

If I look at the first few lines of manifests/init.pp from the Forge module:
```
class pkgng (
  Pattern[/^\/.*/] $pkg_dbdir     = $pkgng::params::pkg_dbdir,
  Pattern[/^\/.*/] $pkg_cachedir  = $pkgng::params::pkg_cachedir,
  Pattern[/^\/.*/] $portsdir      = $pkgng::params::portsdir,
  Array            $options       = [],
  Boolean          $purge_repos_d = true,
  Hash             $repos         = {},
) inherits pkgng::params {
```
Whereas the Github code shows:
```
class pkgng (
  Stdlib::Absolutepath $pkg_dbdir     = $pkgng::params::pkg_dbdir,
  Stdlib::Absolutepath $pkg_cachedir  = $pkgng::params::pkg_cachedir,
  Stdlib::Absolutepath $portsdir      = $pkgng::params::portsdir,
  Array[String]        $options       = [],
  Boolean              $purge_repos_d = true,
  Hash                 $repos         = {},
) inherits pkgng::params {
```

I noticed this difference because my Puppet installation kept adding WITH_PKGNG=YES to make.conf over and over again. Which is the behavior of 1.1.1.

**Comment by SirDice** [comment]
Oh, my dyslexia... Version on Github is 2.1.0, Puppet Forge version is 1.2.0. 

Any chance the version on Forge will be update soon? I now have the Github 2.1.0 version running and it looks to be working correctly.

**Comment by xaque208** [comment]
The forge has been updated for this module.
